version: "3.9"

services:
  db:
    container_name: postgres_db
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: root
      POSTGRES_DB: community
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
