pipeline {
    agent any
    triggers {
        GenericTrigger(
            genericVariables: [
                [key: 'payload', value: '$']
            ],
            token: 'sybyun-test', // GitHub Webhook과 일치하는 토큰
            printContributedVariables: true, // 디버깅 용도
            printPostContent: true // 디버깅 용도
        )
    }

    stages {
        stage('Process Payload') {
            steps {
                script {
                    // JSON 파싱
                    def jsonSlurper = new groovy.json.JsonSlurper()
                    def payloadJson = jsonSlurper.parseText(env.payload)

                    // 필요한 데이터 출력
                    echo "Branch: ${payloadJson.ref}"
                    echo "Repository: ${payloadJson.repository.full_name}"
                    echo "Commit Message: ${payloadJson.head_commit.message}"
                }
            }
        }
    }
}
