pipeline {
    agent any
    tools {
        gradle 'gradle'
    }
    stages {
        stage('Stage Info') {
            steps {
                echo "Branch: ${env.GIT_BRANCH}"
                echo "Commit: ${env.GIT_COMMIT}"
                echo "buildNumber: ${env.BUILD_NUMBER}"
                echo "JobName: ${env.JOB_NAME}"

                echo "Raw Payload: ${params.payload}"
            }
        }
        stage('Git Clone') {
            steps {
                git branch: 'developer', url: 'https://github.com/Dev-SoUni/dieter-community.git'
            }
        }
//         stage('BE-Build') {
//             steps {
//                 dir("./backend") {
//                     sh "./gradlew clean build"
//                 }
//             }
//         }
    }
}