@accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJic3kxNDgyQG5hdmVyLmNvbSIsImlhdCI6MTcyMTYzMTY1MywiZXhwIjoxNzIxNjM1MjUzfQ.xJqXvJxbNUl3c3R2GfBzT1RPQhuL1ZfaLjamYtAO4vY
@refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJic3kxNDgyQG5hdmVyLmNvbSIsImlhdCI6MTcyMTYzMTY1MywiZXhwIjoxNzIxNzE4MDUzfQ.XfhiY0chhnVi6iWnKlSBTr6uFzm50iEupjyj8uZuQ-U

### 로그인
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email": "bsy1482@naver.com",
  "password": "1234"
}

### 토큰 재발급
POST http://localhost:8080/api/auth/refresh
Authorization: Bearer {{accessToken}}
Cookie: refreshToken={{refreshToken}};
Content-Type: application/json

{
  "accessToken": "{{accessToken}}"
}