@id = new

### 팁 전체 조회
GET http://localhost:8080/api/tips

### 꿀팁 검색 (제목)
GET http://localhost:8080/api/tips?title=제목9

### 팁 조회
GET http://localhost:8080/api/tips/{{id}}

### 팁 등록
POST http://localhost:8080/api/tips
Content-Type: application/json

{
  "title": "꿀팁 제목",
  "content": "개굴"
}

### 팁 수정
PATCH http://localhost:8080/api/tips/{{id}}
Content-Type: application/json

{
  "title": "수정 팁 제목",
  "content": "수정 내용"
}

### 팁 삭제
DELETE http://localhost:8080/api/tips/{{id}}