spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/community
    username: dev
    password: root
  data:
    redis:
      host: localhost
      port: 6379

# 나의 환경 변수
jwt:
  secret: 2y2zQFGwJEL/3rbzg+mqBHPYP5wQqn/vG/MCTqVKgBw=
  expiration_time: 3600000 # 1시간